title:               Xia Lin's Code Page
url:                 https://qrcode.xialin-vol.cn
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              夏霖
  url:               https://qrcode.xialin-vol.cn
  email:             superadmin@email.xialin-vol.cn

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
